NAME := {{ name }}

run-goals: {% for goal in sanitized_goals %}run-goal-{{ goal }} {% endfor %}

{% for goal in sanitized_goals %}
run-goal-{{ goal }}:
	sg_shell -tcl spyglass-run-{{ goal }}.tcl

{% endfor -%}

run-gui:
	spyglass -project $(NAME).prj
